import NavBar from "@/components/navbar/NavBar";
import "@styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#e0e0e0]">
        <main>
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
